# Generated by Django 6.0.1 on 2026-02-13 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('frase', models.TextField()),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Apellido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=30, unique=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Listo', 'Listo'), ('Fallido', 'Fallido')], default='Pendiente')),
                ('fuente', models.CharField(max_length=150)),
                ('es_inferido', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Apellido',
                'verbose_name_plural': 'Apellidos',
                'db_table': 'apellido',
                'constraints': [models.UniqueConstraint(fields=('apellido', 'estado'), name='unique_apellido_estado')],
            },
        ),
        migrations.CreateModel(
            name='DistribucionApellidoDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ranking', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apellido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones', to='app.apellido')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apellido_distribuciones', to='app.departamento')),
            ],
            options={
                'verbose_name': 'Distribucion Apellido',
                'verbose_name_plural': 'Distribuciones Apellidos',
                'db_table': 'distribucion_apellido_departamento',
                'ordering': ['ranking'],
            },
        ),
        migrations.CreateModel(
            name='Frases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('PERSONALIDAD', 'Personalidad'), ('SABORES', 'Sabores')], max_length=15)),
                ('frase', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apellido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frases', to='app.apellido')),
            ],
            options={
                'verbose_name': 'Frase',
                'verbose_name_plural': 'Frases',
                'db_table': 'frases',
                'ordering': ['categoria'],
            },
        ),
    ]
